[Rule]
# telegram
cdn-telegram.org
comments.app
contest.com
fragment.com
graph.org
quiz.directory
t.me
tdesktop.com
telega.one
telegra.ph
telegram-cdn.org
telegram.dog
telegram.me
telegram.org
telegram.space
telesco.pe
tg.dev
ton.org
toncenter.com
tx.me
usercontent.dev
# openai
chat.com
chatgpt.com
chatgpt.site
crixet.com
oaistatic.com
oaistatsig.com
oaiusercontent.com
openai.com
sora.com

# CDN & API
openai.com.cdn.cloudflare.net
full:openaiapi-site.azureedge.net
full:openaiassets.blob.core.windows.net
full:openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
full:openaicom.imgix.net
full:openaicomproductionae4b.blob.core.windows.net
full:production-openaicom-storage.azureedge.net
regexp:^chatgpt-async-webps-prod-\S+-\d+\.webpubsub\.azure\.com$

# tracking
full:browser-intake-datadoghq.com @ads
full:o33249.ingest.sentry.io @ads
full:openai.qualtrics.com @ads

# Advanced Voice
chatgpt.livekit.cloud
host.livekit.cloud
turn.livekit.cloud

# остальное напрямую
FINAL,DIRECT
